### ISSUE TITLE
Update for Opsim Version FBS_1.3

### ISSUE THREAD

**Issue by cnsetzer** [LSSTDESC/OpSimSummary#300]
With the new survey strategies being output from the Opsim team, it would be great to be able to still use OpSimSummary to access a summary table of those databases.

As previously, one could use the `subset` flag to select what part of the survey was desired. While I understand it maybe be very hard to separate between WFD and other proposals, maybe we can still use this flag with a special option for `FBS_1.3` so that it is clear to the user that they are getting something different than previously requested.

**Comment by rbiswas4** [comment]
@cnsetzer The [branch](https://github.com/LSSTDESC/OpSimSummary/tree/Issue%23300/fbs_1p3) should address this now that I have implemented the basic steps. You should be able to use this from `SyOpSim.fromOpSimDB` or from `OpSimOutput,fronOpSimDB`.  I have only done quick tests and not sufficiently detailed tests, so let me know if you run into problems. If you are using`OpSimOutput` the syntax for this will be 

```
from opsimsummary import OpSimOutput
dbname = # absolute path to database file in new version `fbs 1.3`
opsout = OpSimOutput.fromOpSimDB(dbname, subset='_all', opsimversion='fbsv1p3')
```

**Comment by cnsetzer** [comment]
Sounds great! Thank you very much for the update, I'll give it a try in a few minutes.

**Comment by rbiswas4** [comment]
@cnsetzer I am updating this code so it will not run on opsim databases which do not have a proposal table. This is because the newer versions of the fbsv1p3 runs have this table, and older versions can have this table added via https://community.lsst.org/t/wfd-metrics-with-the-fbs-output/3970 which @gnarayan has been doing. The new updates will thus work only with such databases, but will be able to distinguish between DDF and WFD.
